CREATE TABLE IF NOT EXISTS IB01_IMAGE_STORE
(
	ADDED_ID	INTEGER	UNSIGNED	NOT NULL	AUTO_INCREMENT PRIMARY KEY,
	HASH		INTEGER UNSIGNED	NOT NULL	COMMENT '画像のハッシュ',
	BODY		MEDIUMBLOB			NOT NULL	COMMENT '画像本体',
	UNIQUE KEY (HASH)
)
ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='画像';
