CREATE TABLE IF NOT EXISTS IB01_INDEX_CHILD
(
	ID			CHAR(36) CHARACTER SET ascii	NOT NULL			COMMENT 'ID',
	OWNER		CHAR(36) CHARACTER SET ascii	NOT NULL			COMMENT '親ID',
	GENERATION	SMALLINT UNSIGNED				NOT NULL DEFAULT 0	COMMENT '世代',
	VOTE_COUNT	SMALLINT UNSIGNED				NOT NULL DEFAULT 0	COMMENT '投票数',
	SCORE		INTEGER							NOT NULL DEFAULT 0	COMMENT 'スコア',
	ENTITY_ID	CHAR(36) CHARACTER SET ascii	NOT NULL			COMMENT '実体ID',
	PRIMARY KEY (ID)
)
ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='子ぼっと索引';
