CREATE TABLE IF NOT EXISTS IB01_INDEX_BOT
(
	ENTITY_ID	CHAR(36) CHARACTER SET ascii		NOT NULL			COMMENT 'ID 兼 実体ID',
	SCORE		INTEGER								NOT NULL DEFAULT 0	COMMENT '累計スコア',
	GENERATION	SMALLINT UNSIGNED					NOT NULL DEFAULT 0	COMMENT '世代',
	PRIMARY KEY (ENTITY_ID)
)
ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ぼっと索引';
