CREATE TABLE IF NOT EXISTS IB01_INDEX_BOT
(
	ADDED_ID	INTEGER	UNSIGNED				NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ENTITY_ID	CHAR(36) CHARACTER SET ascii	NOT NULL			COMMENT 'ID 兼 実体ID',
	THEME		VARCHAR(255)					NOT NULL			COMMENT 'お題',
	SCORE		INTEGER							NOT NULL DEFAULT 0	COMMENT '累計スコア',
	GENERATION	SMALLINT UNSIGNED				NOT NULL DEFAULT 0	COMMENT '世代',
	UNIQUE KEY (ENTITY_ID)
)
ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='ぼっと索引';
