SELECT			ENTITY_ID,
				THEME,
				SCORE,
				GENERATION,
				PUBLICATION
	FROM		IB01_INDEX_BOT
	WHERE		PUBLICATION = TRUE	AND
				THEME COLLATE utf8_unicode_ci LIKE :theme
	ORDER BY	SCORE		DESC,
				ADDED_ID	DESC
	LIMIT		:start, :length;
